### ISSUE TITLE
[CI]도커 파일 추가

### ISSUE THREAD

**Issue by jycforest29** [jycforest29/e-commerce#1]
## 요약
로컬에서 사용한 도커 환경을 파일로 만들어 올린다.
## 할일
- [ ] Dockerfile 파일 추가
- [ ] docker-compose 파일 추가

**Comment by jycforest29** [comment]
헬스 체크 실패

**Comment by jycforest29** [comment]
## 해결방안
- Dockerfile

```
FROM openjdk:11-jre-slim-buster
COPY ./build/libs/commerce-0.0.1-SNAPSHOT.jar /build/libs/commerce-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","/build/libs/commerce-0.0.1-SNAPSHOT.jar"]
```
- FROM 을 사용해 jdk 버전을 설정했다. 해당 프로젝트는 jdk 11 버전을 사용하였고, 경량화를 위해 도커파일에는 jre-slim-buster를 사용하도록 설정했다. 하지만 jre-slim-buster는 비공식적이기 때문에 추후 수정이 필요하다.
- 해당 프로젝트를 jar 파일로 빌드 후 COPY 를 사용해 해당 파일을 컨테이너 외부에서 내부 경로로 옮겨주었다.
- CMD를 사용해 이미지로부터 컨테이너를 생성할 때 최초로 수행할 구문을 명시하였다.

**Comment by jycforest29** [comment]
## 해결방안
- docker-compose.yml (mysql)

스프링부트 어플리케이션외에 도커 컨테이너에 띄울 이미지는 mysql, redis 이다.
기존에 로컬에서 테스트를 진행할때는 일일이 mysql 이미지와 redis 이미지로부터 컨테이너를 생성해 실행하는 방식으로 수행했지만, 다른 개발 환경에서도 원활하게 동작하는 것을 위해 도커 컴포즈를 사용하였다.

```
version: "3"
services:
  databases:
    image: mysql
    container_name: mysql-container
    restart: on-failure
    environment: # 해당 이미지가 사용할 환경 변수 설정
      MYSQL_DATABASE: commercedb
      MYSQL_ROOT_PASSWORD: 1234
    ports: # 호스트에서 접속할 외부 포트 : 도커 내부의 실제 포트(도커 이미지들간의 통신에 사용)
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network
networks:
  test_network:
volumes:
  mysql-data:
```
-> environment 에서의 MYSQL_DATABASE와 MYSQL_ROOT_PASSWORD는 application.properties의 속성을 그대로 맞췄다. 
```
spring.datasource.url=jdbc:mysql://databases:3306/commercedb?createDatabaseIfNotExist=true&autoReconnect=true
spring.datasource.password=1234
```
원래 MYSQL_ROOT_PASSWORD 대신 MYSQL_USER와 MYSQL_PASSWORD를 명시했는데 MYSQL_ROOT_PASSWORD 을 알려달라는 에러가 지속적으로 발생해 수정하였다.
-> ports 에서는 3307 포트를 호스트에서 접속할 외부 포트로 명시하고, 3306 포트를 도커 이미지들간의 통신에 사용하는 내부 포트로 명시하였다. 로컬 컴퓨터에 mysql이 설치되어 있었기 때문에 로컬에서 도커를 사용해 테스트 할때 3306:3306 포트로 연결할 경우 3306 포트를 사용할 수 없다는 에러가 발생하였고, 결국 application.properties에서 url을 localhost:3307 포트로 연결해 테스트를 수행하였다.
하지만 도커 컴포즈를 사용할 경우 도커 이미지들끼리 통신을 하기 때문에 databases(mysql-container의 서비스명):3306 포트를 열어도 3306 포트를 사용할 수 있었다.
-> volume 에서는 mysql-data라는 volume을 사용하도록 하여 도커 컨테이너가 삭제되어도 데이터가 사라지지 않도록 하였다. 
`docker volume ls` 명령어를 사용해 빌드하고 도커 컴포즈도 빌드하여 백그라운드로 실행할 때 마다 현재 존재하는 volume들을 확인했는데 항상 동일하게 존재하는 것을 확인했다. **(하지만 이 부분은 아직 이해 부족)**
-> network 에서는 커스텀 네트워크를 생성해 도커 컴포즈 파일 내의 컨테이너들은 모두 해당 커스텀 네트워크 안에서 통신하도록 하였다.

**Comment by jycforest29** [comment]
## 해결방안
- docker-compose.yml (redis, application)
```
version: "3"
  services:
    redis:
      image: redis
      container_name: redis-container
      restart: on-failure
      hostname: localhost
      ports:
        - "6379:6379"
      networks:
        - test_network
  application:
      container_name: app_for_test
      restart: on-failure
      build:
        context: ./
        dockerfile: Dockerfile
      expose:
        - "8080"
      ports:
        - "8080:8080"
      depends_on:
        - databases
        - redis
```
```
networks:
  test_network:
```
-> 레디스는 매우 간단하므로 넘어간다.
-> 어플리케이션 부분이 매우 어려웠는데 docker-compose.yml을 통해 생성한 mysql, redis 컨테이너와 Dockerfile이 어떻게 연결되는 것인지 감이 안잡혔다. 구글링을 해보니 도커 컴포즈에서 Dockerfile에 대한 빌드를 수행해 스프링부트 어플리케이션 컨테이너를 띄워서 연결한 경우가 보여 동일하게 수행했다. 결과적으로 localhost:8080 포트로 연결이 수행되었다.
