### ISSUE TITLE
[Build]테스트를 포함해 빌드하기

### ISSUE THREAD

**Issue by jycforest29** [jycforest29/e-commerce#5]
## 요약
현재 mysql, redis는 도커를 통해 사용하도록 설정해놓았다.
하지만 이 때문에 로컬 환경에서는 도커 컨테이너를 계속 실행해야만 테스트가 가능했고, 빌드 시 테스트 패키지를 포함하면 테스트가 환경 오류로 실패해 빌드가 되지 않는 문제가 발생했다.

이를 해결할 방법은
- 임베디드(즉 로컬에 설치) 환경에서 테스트
- test container 사용
등이 있고, test container를 사용해 테스트 진행시 자동으로 도커 컨테이너를 생성해 테스트를 정상적으로 진행하고 테스트가 종료시 도커 컨테이너가 삭제되도록 수정하려고 한다.
## 할일
- [ ] test container 의존성 추가 
- [ ] 테스트 파일에 test container 설정 및 동작 확인하기

**Comment by jycforest29** [comment]
DockerComposeContainer를 사용해서 테스트를 실행하면 지속적으로 unknown host exception이 발생한다.

**Comment by jycforest29** [comment]
![스크린샷 2023-03-08 20-10-45](https://user-images.githubusercontent.com/103106183/223698284-73b9bbee-08a0-485d-8107-3d0b9713e99c.png)

위와 같이 테스트 실행시에 실행이 되지만 계속 unknown host exception이 발생한다.

**Comment by jycforest29** [comment]
System.out.println(dockerComposeContainer.getServiceHost("databases_1", 3306)); 을 하니 localhost가 출력된다.

**Comment by jycforest29** [comment]
test 패키지에 resources/application.yml 과 resources/docker-compose-test.yml을 추가했다. 
resources/application.yml)
```
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql://localhost:3307/commercedb
```

resources/docker-compose-test.yml)
```
version: "3"
services:
  databases:
    image: mysql
    environment:
      MYSQL_DATABASE: commercedb
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
```

test 패키지 내부에 testcontainers라는 패키지를 만들어 DockerComposeTestContainer 파일을 생성했다.
**/DockerComposeTestContainer.java)
```
@ActiveProfiles("test") // application-test.yml을 사용하도록 세팅함
// 설정한 프로퍼티에 따라 데이터소스가 적용되므로 none을 사용하여 docker mysql 사용
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Testcontainers
public class DockerComposeTestContainer {
    @Container
    public static final DockerComposeContainer dockerComposeContainer = new DockerComposeContainer(
            new File("src/test/resources/docker-compose-test.yml"))
            .withExposedService("databases_1", 3306, Wait.forListeningPort())
            .withExposedService("redis_1", 6379, Wait.forListeningPort())
            .withLocalCompose(true);
}

```
