### ISSUE TITLE
[CI] 도커 적절하게 사용하기

### ISSUE THREAD

**Issue by jycforest29** [jycforest29/e-commerce#50]
- 어떻게 사용하는 기술인지
- 프로젝트에서 어떻게 적용했는지
- 왜 이 기술이 필요했는지
- 이 기술의 동작원리
- 테스트는 어떻게 하는지

**Comment by jycforest29** [comment]
**어떻게 사용하는 기술인지**

**Comment by jycforest29** [comment]
**프로젝트에서 어떻게 적용했는지**

- Dockerfile
  ```
  FROM openjdk:11
  ARG JAR_FILE=/build/libs/commerce-0.0.1-SNAPSHOT.jar
  COPY ${JAR_FILE} app.jar // 파일을 컨테이너 외부에서 내부 경로로 옮겨줌
  ENTRYPOINT ["java", "-jar", "app.jar"] // 이미지로부터 컨테이너를 생성할 때 최초로 수행할 구문을 명시
  ```
  => 도커는 주로 프로그램 실행을 위해 사용된다. 이를 실행하기 위해선 jar 파일이 필요하고, jar 파일에는 java 가 필요하다. 어떤 환경에서 실행하던 프로젝트의 java 버전과 동일해야 하므로 내가 사용한 jdk 11 버전을 사용한다.

- docker-compose.yml
  ```
  version: "3"
  
  services:
    database:
      image: mysql
      restart: always
      environment: # 해당 이미지가 사용할 환경 변수 설정
        MYSQL_DATABASE: commercedb
        MYSQL_ROOT_PASSWORD: 1234
      ports:
        - "3306"
      volumes:
        - mysql-data:/var/lib/mysql
      command:
        - "--character-set-server=utf8mb4"
        - "--collation-server=utf8mb4_unicode_ci"
      networks:
        - test_network
  
    redis:
      image: redis
      restart: always
      ports:
        - "6379"
      networks:
        - test_network
  
    application:
      restart: always
      build:
        context: ./
        dockerfile: Dockerfile
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/commercedb?createDatabaseIfNotExist=true&autoReconnect=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: 1234
      ports:
        - "8080:8080"
      depends_on:
        - database
        - redis
      networks:
        - test_network
  
  networks:
    test_network:
  
  volumes:
    mysql-data:
  
  ```
=> 내가 도커 컨테이너로 띄운 외부 이미지는 mysql과 redis 이다.
위의 설정을 말로 풀어쓰자면, 나는 mysql과 redis 컨테이너를 생성해 도커파일로 빌드한 application 이라는 컨테이너와 커스텀 네트워크를 사용해 연결해줬다.

사용한 속성을 하나씩 보자면
  - environment : 해당 컨테이너 내부에서 사용할 환경변수 설정
  - ports : 컨테이너 내부에서 사용하는 포트 설정. 상황에 따라 "컨테이너 외부에서 컨테이너와 연결할 포트":"컨테이너 내부에서의 통신에필요한 포트"로 설정 가능
  - volumes : db의 경우 데이터 적재할 곳 설정
  - command : 컨테이너 생성 시 추가할 명령어
------------
그렇다면 도커 컨테이너 내부에서 통신하는 mysql 과 redis 의 속성을 application.yml 을 어떻게 설정해야 할까? 이 부분에서 hostname과 port 번호를 어떻게 할 것인지 매우 헷갈렸다. 특히 추가로 테스트 컨테이너를 사용했는데 테스트는 또 따로 hostname과 port 번호를 설정해줘야 해서 어려웠다.

```
spring:
  config:
    activate:
      on-profile: local-config
  redis:
    host: 127.0.0.1
    port: 6379
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
```
=> 결론적으로 docker-compose.yml 이 존재하면 application.yml에 앞서 환경이 설정되므로 따로 적지 않았다.
