### ISSUE TITLE
[Build] 환경에 따른 application.yml 분리 및 동적 포트 바인딩 사용

### ISSUE THREAD

**Issue by jycforest29** [jycforest29/e-commerce#58]
- 어떻게 사용하는 기술인지
- 프로젝트에서 어떻게 적용했는지
- 왜 이 기술이 필요했는지
- 이 기술의 동작원리
- 테스트는 어떻게 하는지

**Comment by jycforest29** [comment]
- 어떻게 사용하는 기술인지

**Comment by jycforest29** [comment]
- 프로젝트에서 어떻게 적용했는지

**Comment by jycforest29** [comment]
- 왜 이 기술이 필요했는지

**Comment by jycforest29** [comment]
- 이 기술의 동작원리

**Comment by jycforest29** [comment]
- 테스트는 어떻게 하는지

**Comment by jycforest29** [comment]
# DockerComposeTestContainer.java
```
@Slf4j
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Testcontainers
public class DockerComposeTestContainer{
    private static GenericContainer<?> REDIS_CONTAINER;
    private static GenericContainer<?> MYSQL_CONTAINER;
    private static String REDIS_IMAGE = "redis:latest";
    private static String MYSQL_IMAGE = "mysql:latest";

    @BeforeAll
    public static void setUp() throws Exception {
        MYSQL_CONTAINER = new GenericContainer<>(MYSQL_IMAGE)
                .withExposedPorts(3306)
                .withReuse(true);
        REDIS_CONTAINER = new GenericContainer<>(REDIS_IMAGE)
                .withExposedPorts(6379)
                .withReuse(true);
        MYSQL_CONTAINER.start();
        REDIS_CONTAINER.start();

        System.setProperty("spring.redis.host", REDIS_CONTAINER.getHost());
        System.setProperty("spring.redis.port", String.valueOf(REDIS_CONTAINER.getMappedPort(6379)));
    }
}

```
`@AutoConfigureTestDatabase` : 
# main/resources/application.yml
```
spring:
  profiles:
    active: local
    group:
      local: "local-config, common"
      test: "test-config, common"
---
spring:
  config:
    activate:
      on-profile: local-config
  redis:
    host: 127.0.0.1
    port: 6379

---
spring:
  config:
    activate:
      on-profile: test-config
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:///commercedb
  redis:
    host: 127.0.0.1
    port: 6379
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
  main:
    allow-bean-definition-overriding: true
  batch:
    jdbc: # 임베디드 데이터 소스를 사용하지 않을 때도 활성화 가능
      initialize-schema: always
    job:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 8080
jwt:
  secret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345

```
